/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automata1;

import Excepciones.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class VentanaPrueba extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrueba
     */
    public VentanaPrueba() {
        initComponents();
        Alfabeto.setVisible(false);
        Estados.setVisible(false);
        Transiciones.setVisible(false);
        Origen.removeAllItems();
        Transi.removeAllItems();
        Destino.removeAllItems();
        Origen.addItem("");
        Transi.addItem("");
        Destino.addItem("");
        CrearAuto.grabFocus();
    }

    Automata auto1 = new Automata();
    Alfabeto Alfabeto1 = auto1.getAlfabeto();
    Estado_q estado; 
    //Estado_q estadoA = new Estado_q("A",true,false), estadoB = new Estado_q("B",false,true), estadoC = new Estado_q("C",false,false);
    Boolean In = false, Fi = false;
    short conta = 0, contc = 0;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Transiciones = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AgregaTrans = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Origen = new javax.swing.JComboBox();
        Destino = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        FinTransiciones = new javax.swing.JButton();
        Transi = new javax.swing.JComboBox();
        Alfabeto = new javax.swing.JPanel();
        AgregarCaracter = new javax.swing.JButton();
        Caracter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FinCaracter = new javax.swing.JButton();
        CrearAuto = new javax.swing.JButton();
        Estados = new javax.swing.JPanel();
        CrearEstado = new javax.swing.JButton();
        Estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Inicial = new javax.swing.JCheckBox();
        Final = new javax.swing.JCheckBox();
        FinEstados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Automata = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        ShowEst = new javax.swing.JButton();
        ShowAlfa = new javax.swing.JButton();
        C7 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        Graficar = new javax.swing.JButton();
        C2 = new javax.swing.JLabel();
        C10 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C9 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        pizarra = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q7 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q10 = new javax.swing.JLabel();
        Q5 = new javax.swing.JLabel();
        Q8 = new javax.swing.JLabel();
        Q9 = new javax.swing.JLabel();
        Q6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Cadena = new javax.swing.JTextField();
        Validacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Estado Destino:");

        AgregaTrans.setText("Agregar");
        AgregaTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaTransActionPerformed(evt);
            }
        });

        jLabel5.setText("Transiciones:");

        jLabel6.setText("Caracter:");

        Origen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Origen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrigenMouseClicked(evt);
            }
        });
        Origen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OrigenItemStateChanged(evt);
            }
        });

        Destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Estado Origen:");

        FinTransiciones.setText("Fin");
        FinTransiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinTransicionesActionPerformed(evt);
            }
        });

        Transi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout TransicionesLayout = new javax.swing.GroupLayout(Transiciones);
        Transiciones.setLayout(TransicionesLayout);
        TransicionesLayout.setHorizontalGroup(
            TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransicionesLayout.createSequentialGroup()
                .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransicionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Transi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TransicionesLayout.createSequentialGroup()
                        .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TransicionesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TransicionesLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5))
                                    .addGroup(TransicionesLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel6))))
                            .addGroup(TransicionesLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(AgregaTrans)
                                .addGap(18, 18, 18)
                                .addComponent(FinTransiciones)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransicionesLayout.setVerticalGroup(
            TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransicionesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Transi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregaTrans)
                    .addComponent(FinTransiciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AgregarCaracter.setText("Ingresar");
        AgregarCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCaracterActionPerformed(evt);
            }
        });

        Caracter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CaracterFocusGained(evt);
            }
        });
        Caracter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CaracterKeyPressed(evt);
            }
        });

        jLabel2.setText("Alfabeto");

        jLabel3.setText("Caracter: ");

        FinCaracter.setText("Fin");
        FinCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinCaracterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlfabetoLayout = new javax.swing.GroupLayout(Alfabeto);
        Alfabeto.setLayout(AlfabetoLayout);
        AlfabetoLayout.setHorizontalGroup(
            AlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlfabetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlfabetoLayout.createSequentialGroup()
                        .addComponent(AgregarCaracter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinCaracter))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(Caracter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AlfabetoLayout.setVerticalGroup(
            AlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlfabetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caracter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarCaracter)
                    .addComponent(FinCaracter))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        CrearAuto.setText("Crear Autómata");
        CrearAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearAutoActionPerformed(evt);
            }
        });

        CrearEstado.setText("Crear");
        CrearEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEstadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado:");

        jLabel4.setText("Nombre:");

        Inicial.setText("Estado Inicial");
        Inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicialActionPerformed(evt);
            }
        });

        Final.setText("Estado Final");
        Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalActionPerformed(evt);
            }
        });

        FinEstados.setText("Fin");
        FinEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstadosLayout = new javax.swing.GroupLayout(Estados);
        Estados.setLayout(EstadosLayout);
        EstadosLayout.setHorizontalGroup(
            EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadosLayout.createSequentialGroup()
                .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Final)
                            .addComponent(Inicial)))
                    .addGroup(EstadosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(CrearEstado)
                        .addGap(18, 18, 18)
                        .addComponent(FinEstados)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        EstadosLayout.setVerticalGroup(
            EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(Inicial, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(EstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinEstados))
                .addContainerGap())
        );

        Automata.setColumns(20);
        Automata.setRows(5);
        jScrollPane1.setViewportView(Automata);

        jLabel8.setText("Autómata 1");

        ShowEst.setText("Mostrar Estados");
        ShowEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowEstActionPerformed(evt);
            }
        });

        ShowAlfa.setText("Mostrar Alfabeto");
        ShowAlfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAlfaActionPerformed(evt);
            }
        });

        Graficar.setText("Grafo");
        Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarActionPerformed(evt);
            }
        });

        Q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1.setToolTipText("");

        Q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q4.setToolTipText("");

        Q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q3.setToolTipText("");

        Q7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q7.setToolTipText("");

        Q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2.setToolTipText("");

        Q10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q10.setToolTipText("");

        Q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q5.setToolTipText("");

        Q8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q8.setToolTipText("");

        Q9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q9.setToolTipText("");

        Q6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q6.setToolTipText("");

        javax.swing.GroupLayout pizarraLayout = new javax.swing.GroupLayout(pizarra);
        pizarra.setLayout(pizarraLayout);
        pizarraLayout.setHorizontalGroup(
            pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pizarraLayout.setVerticalGroup(
            pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel9.setText("Cadena a Validar:");

        Validacion.setText("Validar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cadena, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Validacion)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Validacion)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Graficar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearAuto)
                            .addComponent(ShowAlfa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ShowEst, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Alfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Alfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(CrearAuto)
                                        .addGap(18, 18, 18)
                                        .addComponent(ShowAlfa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ShowEst)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Transiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Estados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Graficar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregaTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaTransActionPerformed
        try {
            String origen = Origen.getSelectedItem().toString(); 
            String transi = Transi.getSelectedItem().toString();
            String destino = Destino.getSelectedItem().toString();
            char letra = transi.charAt(0);
            Estado_q estado1 = auto1.getEstado(origen); 
            Estado_q estado2 = auto1.getEstado(destino);
            Caracter trans = auto1.getCaracter(letra);
            if(auto1.buscarTrans(auto1.getEstado(origen), auto1.posiCar(letra))==null){
                Transiçao nuevo = new Transiçao(estado2, trans);
                auto1.llenarTransis(auto1.getEstado(origen), auto1.posiCar(letra), nuevo);
                Automata.setText(auto1.mostrarTransiciones());
                System.out.println(nuevo);
                JOptionPane.showMessageDialog(null, "Transicion ingresada exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(null, "El estado seleccionado ya tiene una transicion con el caracter indicado.\nIngrese otro caracter u otro estado");
            }
        } catch (ExcepcionEstadoNoExiste | ExcepcionCaracterNoExiste ex) {
            Logger.getLogger(VentanaPrueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgregaTransActionPerformed

    private void OrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrigenMouseClicked
        
    }//GEN-LAST:event_OrigenMouseClicked

    private void OrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OrigenItemStateChanged
        
    }//GEN-LAST:event_OrigenItemStateChanged

    private void AgregarCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCaracterActionPerformed
        // TODO add your handling code here:
        try {
            if(Caracter.getText().length()==1){
                if(conta == 0){
                    auto1.agregaCar(Caracter.getText().charAt(0));
                    Transi.addItem(Caracter.getText());
                    Transi.repaint();
                }
                JOptionPane.showMessageDialog(Transi, "El caracter " + Caracter.getText() + " ha sido ingresado con éxito", null, JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(Transi, "Para el alfabeto es necesario ingresar\nsolamente caracteres como elementos", null, JOptionPane.ERROR_MESSAGE);
            }
            Caracter.setText("");
            Caracter.grabFocus();
        } catch (ExcepcionCaracterYaExiste ex) {
            JOptionPane.showMessageDialog(Transi, ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            Caracter.setText("");
            Caracter.grabFocus();
        }
    }//GEN-LAST:event_AgregarCaracterActionPerformed

    private void CaracterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CaracterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CaracterFocusGained

    private void CaracterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CaracterKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            AgregarCaracterActionPerformed(null);
    }//GEN-LAST:event_CaracterKeyPressed

    private void FinCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinCaracterActionPerformed
        // TODO add your handling code here:
        Caracter.setText("");
        Estados.setVisible(true);
        Alfabeto.setVisible(false);
        Estado.grabFocus();
    }//GEN-LAST:event_FinCaracterActionPerformed

    private void CrearAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearAutoActionPerformed
        auto1 = new Automata();
        JOptionPane.showMessageDialog(null, "Primer autómata creado con éxito", null, JOptionPane.INFORMATION_MESSAGE);
        Alfabeto.setVisible(true);
        Caracter.grabFocus();
    }//GEN-LAST:event_CrearAutoActionPerformed

    private void CrearEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEstadoActionPerformed
        try {
            // TODO add your handling code here:
            estado = new Estado_q(Estado.getText(), In, Fi);
            if(auto1.verificarInicial(estado)==true)
                JOptionPane.showMessageDialog(null, "Ya existe un estado inicial en el autómata, por favor cambie este campo");
            else{
                auto1.agregaEst(estado);
                Origen.addItem(Estado.getText());
                Origen.repaint();
                Destino.addItem(Estado.getText());
                Destino.repaint();
                JOptionPane.showMessageDialog(null, estado.toString(), null, JOptionPane.INFORMATION_MESSAGE);
            }
            Estado.setText("");
            Estado.grabFocus();
        } catch (ExcepcionEstadoYaExiste ex) {
            JOptionPane.showMessageDialog(Transi, ex.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearEstadoActionPerformed

    private void InicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicialActionPerformed
        // TODO add your handling code here:
        if(Inicial.isSelected())
            In = true;
        else
            In = false;
    }//GEN-LAST:event_InicialActionPerformed

    private void FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalActionPerformed
        // TODO add your handling code here:
        if(Final.isSelected())
            Fi = true;
        else
            Fi = false;
    }//GEN-LAST:event_FinalActionPerformed

    private void FinEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinEstadosActionPerformed
        // TODO add your handling code here:
        Estado.setText("");
        auto1.iniciaVec();
        Transiciones.setVisible(true);
        Estados.setVisible(false);
    }//GEN-LAST:event_FinEstadosActionPerformed

    private void ShowAlfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAlfaActionPerformed
        Automata.setText(Automata.getText() + "\n" + auto1.getAlfabeto().toString());
    }//GEN-LAST:event_ShowAlfaActionPerformed

    private void ShowEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowEstActionPerformed
        // TODO add your handling code here:
        Automata.setText(auto1.mostrarEstados() + "\n" + auto1.mostrarTransiciones());
    }//GEN-LAST:event_ShowEstActionPerformed

    //timy
    public void limpiar(){
            
        Q1.setText(null);
        Q1.setBackground(null);
        Q2.setText(null);
        Q2.setBackground(null);        
        Q3.setText(null);
        Q3.setBackground(null);   
        Q4.setText(null);
        Q4.setBackground(null);
        Q5.setText(null);
        Q5.setBackground(null);
        Q6.setText(null);
        Q6.setBackground(null);
        Q7.setText(null);
        Q7.setBackground(null);
        Q8.setText(null);
        Q8.setBackground(null);
        Q9.setText(null);
        Q9.setBackground(null);
        Q10.setText(null);
        Q10.setBackground(null);
        
        C1.setText(null);
        C2.setText(null);
        C3.setText(null);
        C4.setText(null);
        C5.setText(null);
        C6.setText(null);
        C7.setText(null);
        C8.setText(null);
        C9.setText(null);
        C10.setText(null);
     
    }
    //timy
    public void colores(){
        C1.setForeground(Color.RED);
        C2.setForeground(Color.BLACK);
        C3.setForeground(Color.BLUE);
        C4.setForeground(Color.CYAN);
        C5.setForeground(Color.YELLOW);
        C6.setForeground(Color.PINK);
        C7.setForeground(Color.GREEN);
        C8.setForeground(Color.LIGHT_GRAY);
        C9.setForeground(Color.MAGENTA);
        C10.setForeground(Color.ORANGE);
    }
       
    
    public void linea(Graphics g,int x1,int y1, int x2,int y2, Color color){
        g.setColor(color);
        g.drawLine(x1, y1, x2, y2);   
    }
    
    public  JLabel buscarlabel(String nombre){
        JLabel Q = null;
        
        if(nombre==Q1.getText())
            Q=Q1;
        if(nombre==Q2.getText())
            Q=Q2;
        if(nombre==Q3.getText())
            Q=Q3;
        if(nombre==Q4.getText())
            Q=Q4;
        if(nombre==Q5.getText())
            Q=Q5;
        if(nombre==Q6.getText())
            Q=Q6;
        if(nombre==Q7.getText())
            Q=Q7;
        if(nombre==Q8.getText())
            Q=Q8;
        if(nombre==Q9.getText())
            Q=Q9;
        if(nombre==Q10.getText())
            Q=Q10;
        
        
        return Q;
    }
    
    public  JLabel buscarletra(String nombre){
        JLabel Q = null;
        
        if(nombre.equals(C1.getText()))
            Q=C1;
        if(nombre.equals(C2.getText()))
            Q=C2;
        if(nombre.equals(C3.getText()))
            Q=C3;
        if(nombre.equals(C4.getText()))
            Q=C4;
        if(nombre.equals(C5.getText()))
            Q=C5;
        if(nombre.equals(C6.getText()))
            Q=C6;
        if(nombre.equals(C7.getText()))
            Q=C7;
        if(nombre.equals(C8.getText()))
            Q=C8;
        if(nombre.equals(C9.getText()))
            Q=C9;
        if(nombre.equals(C10.getText()))
            Q=C10;

        return Q;
    }
    
    public  Color buscarcolor(JLabel nombre){
        Color Q = Color.cyan;
        
        if(nombre==C1){
            Q=Color.RED;
            return Q;
        }
           
        if(nombre==C2){
            Q=Color.BLACK;
            return Q;
        }
        if(nombre==C3){
            Q=Color.BLUE;
            return Q;
        }
        if(nombre==C4){
            Q=Color.CYAN;
            return Q;
        }
        if(nombre==C5){
            Q=Color.YELLOW;
            return Q;
        }
        if(nombre==C6){
            Q=Color.PINK;
            return Q;
        }
        if(nombre==C7){
            Q=Color.GREEN;
            return Q;
        }
        if(nombre==C8){
            Q=Color.LIGHT_GRAY;
            return Q;
        }
        if(nombre==C9){
            Q=Color.MAGENTA;
            return Q;
        }
        if(nombre==C10){
            Q=Color.ORANGE;
            return Q;
        }

        return Q;
    }
    
    public void trans(Automata auto){
        Transiçao nuevo = new Transiçao();
        Estado_q Einicial = new Estado_q();
        Estado_q Efinal = new Estado_q();
        JLabel lab = new JLabel();
        JLabel lab2= new JLabel();
        JLabel letra= new JLabel();
        int tam=0;
        int x1,y1,x2,y2;
        Einicial=auto.getEstados().getInicio().getEstSig();
        
        for(int i=1;i<=auto.getEstados().getTamaño();i++){
            
            lab=buscarlabel(Einicial.getNombre());
            short x=0;
            tam=Einicial.getTransiçaos().length;
            
            x1=lab.getX();
            y1=lab.getY();
            
            for(int j=1;j<=tam;j++){
                
                nuevo=Einicial.getTransiçao(x);
                Efinal=nuevo.getDestino();
                lab2=buscarlabel(Efinal.getNombre());
                x2=lab2.getX();
                y2=lab2.getY();
                
                char n=nuevo.getTrans().getCaracter();
                String m=String.valueOf(n);
                
                letra=buscarletra(m);
                Color col=buscarcolor(letra);
                
                
                if(lab==lab2){
                    linea(pizarra.getGraphics(),x1,y1,x1,y1-20,col);
                }
                else if(lab!=lab2){
                    linea(pizarra.getGraphics(),x1,y1,x2,y2+j*15,col);
                }
                x++;
            }

            Einicial=Einicial.getEstSig();
        }
        
    }
    
    //timy
    public void alfabeto()throws ExcepcionCaracterNoExiste{
        short tam = Alfabeto1.getTamaño();
        short x=0;
        
        if(x<tam){
            C1.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C2.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C3.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C4.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C5.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C6.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C7.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C8.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C9.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
        if(x<tam){
            C10.setText(String.valueOf(Alfabeto1.getChar2(x)));
            x++;
        }
    }
    
    //timy
    private void crearestado(JLabel x,Estado_q iterador){
        if(iterador.isFinal()==false&&iterador!=auto1.getEstados().getFin()){
                x.setText(iterador.getNombre());
                x.setBackground(Color.white);
                x.setOpaque(true); 
                if(iterador.isInic()==true)
                    x.setForeground(Color.red);
                iterador=iterador.getEstSig();
            }
            else if(iterador.isFinal()==true&&iterador!=auto1.getEstados().getFin()){
                x.setText(iterador.getNombre());
                x.setBackground(Color.cyan);
                x.setOpaque(true);
                if(iterador.isInic()==true)
                    x.setForeground(Color.red); 
                iterador=iterador.getEstSig();
            }
    }
 
    private void GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarActionPerformed

        limpiar();
        try {

            limpiar();
            colores();

            Estado_q iterador = auto1.getEstados().getInicio().getEstSig();
            alfabeto();

            int n=auto1.getEstados().getTamaño();
            int cont=1;
            int x=Q1.getX();
            int y=Q1.getY();

            //estado1
            if(cont<=n){
                crearestado(Q1,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 2
            if(cont<=n){
                crearestado(Q2,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 3
            if(cont<=n){
                crearestado(Q3,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 4
            if(cont<=n){
                crearestado(Q4,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 5
            if(cont<=n){
                crearestado(Q5,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 6
            if(cont<=n){
                crearestado(Q6,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 7
            if(cont<=n){
                crearestado(Q7,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 8
            if(cont<=n){
                crearestado(Q8,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 9
            if(cont<=n){
                crearestado(Q9,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            //estado 10
            if(cont<=n){
                crearestado(Q10,iterador);
                iterador=iterador.getEstSig();
                cont++;
            }
            
            
            trans(auto1);

            //TRANSICIONES

            /*lineaRED(pizarra.getGraphics(),Q1.getX()+05,Q1.getY()+05,Q2.getX()+05,Q2.getY()+05);
            lineaRED(pizarra.getGraphics(),Q1.getX()+10,Q1.getY()+10,Q3.getX()+10,Q3.getY()+10);
            lineaRED(pizarra.getGraphics(),Q1.getX()+15,Q1.getY()+15,Q4.getX()+15,Q4.getY()+15);
            lineaRED(pizarra.getGraphics(),Q1.getX()+20,Q1.getY()+20,Q5.getX()+20,Q5.getY()+20);
            lineaRED(pizarra.getGraphics(),Q1.getX(),Q1.getY(),Q6.getX(),Q6.getY());
            lineaRED(pizarra.getGraphics(),Q1.getX(),Q1.getY(),Q7.getX(),Q7.getY());
            lineaRED(pizarra.getGraphics(),Q1.getX(),Q1.getY(),Q8.getX(),Q8.getY());
            lineaRED(pizarra.getGraphics(),Q1.getX(),Q1.getY(),Q9.getX(),Q9.getY());
            lineaRED(pizarra.getGraphics(),Q1.getX(),Q1.getY(),Q10.getX(),Q10.getY());*/

        } catch (ExcepcionCaracterNoExiste ex) {
            Logger.getLogger(VentanaPrueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GraficarActionPerformed

    private void FinTransicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinTransicionesActionPerformed
        // TODO add your handling code here:
        if(auto1.verificarTransiçaos()==true){
            JOptionPane.showMessageDialog(null, "Transiciones Completas ;)");
        }
        else{
            JOptionPane.showMessageDialog(null, "Hay alguna transición que no ha sido ingresada.\nPor favor, verifique los datos ingresados");
        }
    }//GEN-LAST:event_FinTransicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregaTrans;
    private javax.swing.JButton AgregarCaracter;
    private javax.swing.JPanel Alfabeto;
    private javax.swing.JTextArea Automata;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C10;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JTextField Cadena;
    private javax.swing.JTextField Caracter;
    private javax.swing.JButton CrearAuto;
    private javax.swing.JButton CrearEstado;
    private javax.swing.JComboBox Destino;
    private javax.swing.JTextField Estado;
    private javax.swing.JPanel Estados;
    private javax.swing.JButton FinCaracter;
    private javax.swing.JButton FinEstados;
    private javax.swing.JButton FinTransiciones;
    private javax.swing.JCheckBox Final;
    private javax.swing.JButton Graficar;
    private javax.swing.JCheckBox Inicial;
    private javax.swing.JComboBox Origen;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q10;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Q6;
    private javax.swing.JLabel Q7;
    private javax.swing.JLabel Q8;
    private javax.swing.JLabel Q9;
    private javax.swing.JButton ShowAlfa;
    private javax.swing.JButton ShowEst;
    private javax.swing.JComboBox Transi;
    private javax.swing.JPanel Transiciones;
    private javax.swing.JButton Validacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pizarra;
    // End of variables declaration//GEN-END:variables
}
